import { Skill } from '../types'

export const SKILL_DEFINITIONS: Omit<Skill, 'modifier'>[] = [
    {name:"Acrobatics", ranks: 20, ability: "dex", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/acrobatics'},  
    {name:"Appraise", ranks: 20, ability: "int", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/appraise'},
    {name:"Bluff", ranks: 20, ability: "cha", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/bluff'},
    {name:"Climb", ranks: 20, ability: "str", class_skill: true, acp: true, requires_training: true, description: "https://www.d20pfsrd.com/skills/climb"}, 
    {name:"Craft", ranks: 20, ability: "int", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/craft'}, 
    {name:"Diplomacy", ranks: 20, ability: "cha", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/diplomacy'}, 
    {name:"Disable Device", ranks: 20, ability: "dex", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/disable-device'}, 
    {name:"Disguise", ranks: 20, ability: "cha", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/disguise'}, 
    {name:"Escape Artist", ranks: 20, ability: "dex", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/escape-artist'}, 
    {name:"Fly", ranks: 20, ability: "dex", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/fly'}, 
    {name:"Handle Animal", ranks: 20, ability: "wis", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/handle-animal'}, 
    {name:"Heal", ranks: 20, ability: "wis", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/heal'}, 
    {name:"Intimidate", ranks: 20, ability: "cha", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/intimidate'}, 
    {name:"Knowledge Arcana", ranks: 20, ability: "int", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/knowledge'}, 
    {name:"Knowledge Dungeoneering", ranks: 20, ability: "int", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/knowledge'}, 
    {name:"Knowledge Engineering", ranks: 20, ability: "int", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/knowledge'}, 
    {name:"Knowledge Geography", ranks: 20, ability: "int", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/knowledge'}, 
    {name:"Knowledge History", ranks: 20, ability: "int", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/knowledge'}, 
    {name:"Knowledge Local", ranks: 20, ability: "int", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/knowledge'}, 
    {name:"Knowledge Nature", ranks: 20, ability: "int", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/knowledge'}, 
    {name:"Knowledge Nobility", ranks: 20, ability: "int", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/knowledge'}, 
    {name:"Knowledge Planes", ranks: 20, ability: "int", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/knowledge'}, 
    {name:"Knowledge Religion", ranks: 20, ability: "int", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/knowledge'}, 
    {name:"Linguistics", ranks: 20, ability: "wis", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/linguistics'}, 
    {name:"Perception", ranks: 20, ability: "wis", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/perception'}, 
    {name:"Perform", ranks: 20, ability: "cha", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/perform'}, 
    {name:"Profession", ranks: 20, ability: "wis", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/profession'}, 
    {name:"Ride", ranks: 20, ability: "dex", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/ride'}, 
    {name:"Sense Motive", ranks: 20, ability: "wis", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/sense-motive'}, 
    {name:"Sleight of Hand", ranks: 20, ability: "dex", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/sleight-of-hand'}, 
    {name:"Spellcraft", ranks: 20, ability: "int", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/spellcraft'}, 
    {name:"Stealth", ranks: 20, ability: "dex", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/stealth'}, 
    {name:"Survival", ranks: 20, ability: "wis", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/survival'}, 
    {name:"Swim",  ranks: 0, ability: "str", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/swim'}, 
    {name:"Use Magic Device", ranks: 20, ability: "cha", class_skill: true, acp: true, requires_training: true, description: 'https://www.d20pfsrd.com/skills/use-magic-device'}];